-- テーブル
INSERT INTO todo (content) VALUES ('Hello, Onsen UI !');
INSERT INTO todo (content) VALUES ('Greetings Angular Developers, Onsen UI Team, Samurais, American, Japanese, German Superheroes ...');
INSERT INTO todo (content) VALUES ('Create some New Apps with Angular 4 & Onsen UI 2');
INSERT INTO todo (content) VALUES ('Learn Onsen UI');
INSERT INTO todo (content) VALUES ('Learn Angular');
INSERT INTO todo (content) VALUES ('Learn RxJS');
INSERT INTO todo (content) VALUES ('Create New Angular Apps with Redux');
INSERT INTO todo (content) VALUES ('Create a New Blog');
INSERT INTO todo (content) VALUES ('Write new Angular Tutorials');
INSERT INTO todo (content) VALUES ('Code Angular Documentation');
INSERT INTO todo (content) VALUES ('Work Hard, Be Kind, Do More.');
INSERT INTO todo (content) VALUES ('Save the World. Get a Kiss From My Dream Spirit. Keras an Oneiros');
INSERT INTO todo (content) VALUES ('Learn Ionic 3');
INSERT INTO todo (content) VALUES ('Write a Book about Angular');
INSERT INTO todo (content) VALUES ('Write a Book about Progressive Web App');
INSERT INTO todo (content) VALUES ('Hook Up The Backend to Firebase Platform');
INSERT INTO todo (content) VALUES ('Start TDD in Angular');
INSERT INTO todo (content) VALUES ('Contribute in Angular Repositories');
INSERT INTO todo (content) VALUES ('Contribute in Onsen UI Repositories');
INSERT INTO todo (content) VALUES ('Code with passion. Code all the time. AngularFire of Desire. :)');
INSERT INTO todo (content) VALUES ('Hello World from Android Mobile Device. I want to get on all Desktops. Can anybody help me???');
INSERT INTO todo (content) VALUES ('Google create New Android Desktop OS. Cloud OS. ChromeBooks ...');
INSERT INTO todo (content) VALUES ('Welcome to the Future. An Open Source World. A Google World.');
INSERT INTO todo (content) VALUES ('Imagine/Dream the World in 50 Years. Then Build It Now.');
INSERT INTO todo (content) VALUES ('Thank you for your interest');
INSERT INTO todo (content) VALUES ('This app is powered by Angular + Onsen UI + NgRx');
INSERT INTO todo (content) VALUES ('Build the app with @angular/cli	');
INSERT INTO todo (content) VALUES ('Build the app with Webpack');
